/* eslint-disable prettier/prettier */

const farmersFakeList = [
  {
    name: 'Amy Farha',
    avatar_url: 'https://local.pt',
    age: 45,
    farmlands: 2,
    trees: 345,
    subcategory: 'comercial',
  },
  {
    name: 'Chris Jackson',
    avatar_url: 'https://local.pt',
    age: 45,
    farmlands: 2,
    trees: 345,
    subcategory: 'comercial',
  },
  // {
  //   name: 'Amy Farha',
  //   avatar_url: '#',
  //   age: 45,
  //   farmlands: 2,
  //   trees: 345,
  //   subcategory: 'comercial',
  // },
  // {
  //   name: 'Chris Jackson',
  //   avatar_url: '#',
  //   age: 45,
  //   farmlands: 2,
  //   trees: 345,
  //   subcategory: 'comercial',
  // },
  // {
  //   name: 'Amy Farha',
  //   avatar_url: '#',
  //   age: 45,
  //   farmlands: 2,
  //   trees: 345,
  //   subcategory: 'comercial',
  // },
  // {
  //   name: 'Chris Jackson',
  //   avatar_url: '#',
  //   age: 45,
  //   farmlands: 2,
  //   trees: 345,
  //   subcategory: 'comercial',
  // },
  // {
  //   name: 'Amy Farha',
  //   avatar_url: '#',
  //   age: 45,
  //   farmlands: 2,
  //   trees: 345,
  //   subcategory: 'comercial',
  // },
  // {
  //   name: 'Amy Farha',
  //   avatar_url: '#',
  //   age: 45,
  //   farmlands: 2,
  //   trees: 345,
  //   subcategory: 'comercial',
  // },
  // {
  //   name: 'Chris Jackson',
  //   avatar_url: '#',
  //   age: 45,
  //   farmlands: 2,
  //   trees: 345,
  //   subcategory: 'comercial',
  // },
  // {
  //   name: 'Amy Farha',
  //   avatar_url: '#',
  //   age: 45,
  //   farmlands: 2,
  //   trees: 345,
  //   subcategory: 'comercial',
  // },
  // {
  //   name: 'Chris Jackson',
  //   avatar_url: '#',
  //   age: 45,
  //   farmlands: 2,
  //   trees: 345,
  //   subcategory: 'comercial',
  // },
  // {
  //   name: 'Amy Farha',
  //   avatar_url: '#',
  //   age: 45,
  //   farmlands: 2,
  //   trees: 345,
  //   subcategory: 'comercial',
  // },
  // {
  //   name: 'Chris Jackson',
  //   avatar_url: '#',
  //   age: 45,
  //   farmlands: 2,
  //   trees: 345,
  //   subcategory: 'comercial',
  // },
  // {
  //   name: 'Amy Farha',
  //   avatar_url: '#',
  //   age: 45,
  //   farmlands: 2,
  //   trees: 345,
  //   subcategory: 'comercial',
  // },
  // {
  //   name: 'Amy Farha',
  //   avatar_url: '#',
  //   age: 45,
  //   farmlands: 2,
  //   trees: 345,
  //   subcategory: 'comercial',
  // },
  // {
  //   name: 'Chris Jackson',
  //   avatar_url: '#',
  //   age: 45,
  //   farmlands: 2,
  //   trees: 345,
  //   subcategory: 'comercial',
  // },
  // {
  //   name: 'Amy Farha',
  //   avatar_url: '#',
  //   age: 45,
  //   farmlands: 2,
  //   trees: 345,
  //   subcategory: 'comercial',
  // },
  // {
  //   name: 'Chris Jackson',
  //   avatar_url: '#',
  //   age: 45,
  //   farmlands: 2,
  //   trees: 345,
  //   subcategory: 'comercial',
  // },
  // {
  //   name: 'Amy Farha',
  //   avatar_url: '#',
  //   age: 45,
  //   farmlands: 2,
  //   trees: 345,
  //   subcategory: 'comercial',
  // },
  // {
  //   name: 'Chris Jackson',
  //   avatar_url: '#',
  //   age: 45,
  //   farmlands: 2,
  //   trees: 345,
  //   subcategory: 'comercial',
  // },
  // {
  //   name: 'Amy Farha',
  //   avatar_url: '#',
  //   age: 45,
  //   farmlands: 2,
  //   trees: 345,
  //   subcategory: 'comercial',
  // },
];

export default farmersFakeList;