/* eslint-disable prettier/prettier */
const countries3 = [
  {key: 'Essuatíni', value: 'Essuatíni'},
  {key: 'Índia', value: 'Índia'},
  {key: 'Maláui', value: 'Maláui'},
  {key: 'Portugal', value: 'Portugal'},
  {key: 'Tanzânia', value: 'Tanzânia'},
  {key: 'Zâmbia', value: 'Zâmbia'},
  {key: 'Zimbábue', value: 'Zimbábue'},
  {key: 'África do Sul', value: 'África do Sul'},

  {key: 'Afeganistão', value: 'Afeganistão'},
  {key: 'Albânia', value: 'Albânia'},
  {key: 'Alemanha', value: 'Alemanha'},

  {key: 'Andorra', value: 'Andorra'},
  {key: 'Angola', value: 'Angola'},
  {key: 'Antiga e Barbuda', value: 'Antiga e Barbuda'},

  {key: 'Arábia Saudita', value: 'Arábia Saudita'},
  {key: 'Argélia', value: 'Argélia'},
  {key: 'Argentina', value: 'Argentina'},
  {key: 'Arménia', value: 'Arménia'},
  {key: 'Austrália', value: 'Austrália'},
  {key: 'Áustria', value: 'Áustria'},
  {key: 'Azerbaijão', value: 'Azerbaijão'},
  {key: 'Bahamas', value: 'Bahamas'},
  {key: 'Bangladexe', value: 'Bangladexe'},
  {key: 'Barbados', value: 'Barbados'},
  {key: 'Barém', value: 'Barém'},
  {key: 'Bélgica', value: 'Bélgica'},
  {key: 'Belize', value: 'Belize'},
  {key: 'Benim', value: 'Benim'},
  {key: 'Bielorrússia', value: 'Bielorrússia'},
  {key: 'Bolívia', value: 'Bolívia'},
  {key: 'Bósnia e Herzegovina', value: 'Bósnia e Herzegovina'},
  {key: 'Botsuana', value: 'Botsuana'},
  {key: 'Brasil', value: 'Brasil'},
  {key: 'Brunei', value: 'Brunei'},
  {key: 'Bulgária', value: 'Bulgária'},

  {key: 'Burquina Faso', value: 'Burquina Faso'},
  {key: 'Burúndi', value: 'Burúndi'},
  {key: 'Butão', value: 'Butão'},
  {key: 'Cabo Verde', value: 'Cabo Verde'},
  {key: 'Camarões', value: 'Camarões'},
  {key: 'Camboja', value: 'Camboja'},
  {key: 'Canadá', value: 'Canadá'},
  {key: 'Catar', value: 'Catar'},
  {key: 'Cazaquistão', value: 'Cazaquistão'},
  {key: 'Chade', value: 'Chade'},
  {key: 'Chile', value: 'Chile'},
  {key: 'China', value: 'China'},
  {key: 'Chipre', value: 'Chipre'},
  {key: 'Colômbia', value: 'Colômbia'},
  {key: 'Comores', value: 'Comores'},
  {key: 'Congo-Brazzaville', value: 'Congo-Brazzaville'},
  {key: 'Coreia do Norte', value: 'Coreia do Norte'},
  {key: 'Coreia do Sul', value: 'Coreia do Sul'},
  {key: 'Costa do Marfim', value: 'Costa do Marfim'},
  {key: 'Costa Rica', value: 'Costa Rica'},
  {key: 'Croácia', value: 'Croácia'},
  {key: 'Cuba', value: 'Cuba'},
  {key: 'Dinamarca', value: 'Dinamarca'},
  {key: 'Dominica', value: 'Dominica'},
  {key: 'Egito', value: 'Egito'},
  {key: 'Emirados Árabes Unidos', value: 'Emirados Árabes Unidos'},
  {key: 'Equador', value: 'Equador'},
  {key: 'Eritreia', value: 'Eritreia'},
  {key: 'Eslováquia', value: 'Eslováquia'},
  {key: 'Eslovénia', value: 'Eslovénia'},
  {key: 'Espanha', value: 'Espanha'},
  {key: 'Estado da Palestina', value: 'Estado da Palestina'},
  {key: 'Estados Unidos de América', value: 'Estados Unidos de América'},
  {key: 'Estónia', value: 'Estónia'},
  {key: 'Etiópia', value: 'Etiópia'},
  {key: 'Fiji', value: 'Fiji'},
  {key: 'Filipinas', value: 'Filipinas'},
  {key: 'Finlândia', value: 'Finlândia'},
  {key: 'França', value: 'França'},
  {key: 'Gabão', value: 'Gabão'},
  {key: 'Gâmbia', value: 'Gâmbia'},
  {key: 'Gana', value: 'Gana'},
  {key: 'Geórgia', value: 'Geórgia'},
  {key: 'Granada', value: 'Granada'},
  {key: 'Grécia', value: 'Grécia'},
  {key: 'Guatemala', value: 'Guatemala'},
  {key: 'Guiana', value: 'Guiana'},
  {key: 'Guiné', value: 'Guiné'},
  {key: 'Guiné Equatorial', value: 'Guiné Equatorial'},
  {key: 'Guiné-Bissau', value: 'Guiné-Bissau'},
  {key: 'Haiti', value: 'Haiti'},
  {key: 'Honduras', value: 'Honduras'},
  {key: 'Hungria', value: 'Hungria'},
  {key: 'Iémen', value: 'Iémen'},
  {key: 'Ilhas Marechal', value: 'Ilhas Marechal'},
  {key: 'Indonésia', value: 'Indonésia'},
  {key: 'Irão', value: 'Irão'},
  {key: 'Iraque', value: 'Iraque'},
  {key: 'Irlanda', value: 'Irlanda'},
  {key: 'Islândia', value: 'Islândia'},
  {key: 'Israel', value: 'Israel'},
  {key: 'Itália', value: 'Itália'},
  {key: 'Jamaica', value: 'Jamaica'},
  {key: 'Japão', value: 'Japão'},
  {key: 'Jibuti', value: 'Jibuti'},
  {key: 'Jordânia', value: 'Jordânia'},
  {key: 'Laus', value: 'Laus'},
  {key: 'Lesoto', value: 'Lesoto'},
  {key: 'Letónia', value: 'Letónia'},
  {key: 'Líbano', value: 'Líbano'},
  {key: 'Libéria', value: 'Libéria'},
  {key: 'Líbia', value: 'Líbia'},
  {key: 'Listenstaine', value: 'Listenstaine'},
  {key: 'Lituânia', value: 'Lituânia'},
  {key: 'Luxemburgo', value: 'Luxemburgo'},
  {key: 'Macedónia do Norte', value: 'Macedónia do Norte'},
  {key: 'Madagáscar', value: 'Madagáscar'},
  {key: 'Malásia', value: 'Malásia'},
  {key: 'Maldivas', value: 'Maldivas'},
  {key: 'Mali', value: 'Mali'},
  {key: 'Malta', value: 'Malta'},
  {key: 'Marrocos', value: 'Marrocos'},
  {key: 'Maurícia', value: 'Maurícia'},
  {key: 'Mauritânia', value: 'Mauritânia'},
  {key: 'México', value: 'México'},
  {key: 'Mianmar', value: 'Mianmar'},
  {key: 'Micronésia', value: 'Micronésia'},
  {key: 'Moçambique', value: 'Moçambique'},
  {key: 'Moldávia', value: 'Moldávia'},
  {key: 'Mónaco', value: 'Mónaco'},
  {key: 'Mongólia', value: 'Mongólia'},
  {key: 'Montenegro', value: 'Montenegro'},
  {key: 'Namíbia', value: 'Namíbia'},
  {key: 'Nauru', value: 'Nauru'},
  {key: 'Nepal', value: 'Nepal'},
  {key: 'Nicarágua', value: 'Nicarágua'},
  {key: 'Níger', value: 'Níger'},
  {key: 'Nigéria', value: 'Nigéria'},
  {key: 'Noruega', value: 'Noruega'},
  {key: 'Nova Zelândia', value: 'Nova Zelândia'},
  {key: 'Omã', value: 'Omã'},
  {key: 'Países Baixos', value: 'Países Baixos'},
  {key: 'Palau', value: 'Palau'},
  {key: 'Panamá', value: 'Panamá'},
  {key: 'Papua Nova Guiné', value: 'Papua Nova Guiné'},
  {key: 'Paquistão', value: 'Paquistão'},
  {key: 'Paraguai', value: 'Paraguai'},
  {key: 'Peru', value: 'Peru'},
  {key: 'Polónia', value: 'Polónia'},
  {key: 'Quénia', value: 'Quénia'},
  {key: 'Quirguistão', value: 'Quirguistão'},
  {key: 'Quiribáti', value: 'Quiribáti'},
  {key: 'Reino Unido', value: 'Reino Unido'},
  {key: 'República Centro-Africana', value: 'República Centro-Africana'},
  {key: 'República Checa', value: 'República Checa'},
  {
    key: 'República Democrática do Congo',
    value: 'República Democrática do Congo',
  },
  {key: 'República Dominicana', value: 'República Dominicana'},
  {key: 'Roménia', value: 'Roménia'},
  {key: 'Ruanda', value: 'Ruanda'},
  {key: 'Rússia', value: 'Rússia'},
  {key: 'Salomão', value: 'Salomão'},
  {key: 'Salvador', value: 'Salvador'},
  {key: 'Samoa', value: 'Samoa'},
  {key: 'Santa Lúcia', value: 'Santa Lúcia'},
  {key: 'São Cristóvão e Neves', value: 'São Cristóvão e Neves'},
  {key: 'São Marinho', value: 'São Marinho'},
  {key: 'São Tomé e Príncipe', value: 'São Tomé e Príncipe'},
  {key: 'São Vicente e Granadinas', value: 'São Vicente e Granadinas'},
  {key: 'Seicheles', value: 'Seicheles'},
  {key: 'Senegal', value: 'Senegal'},
  {key: 'Serra Leoa', value: 'Serra Leoa'},
  {key: 'Sérvia', value: 'Sérvia'},
  {key: 'Singapura', value: 'Singapura'},
  {key: 'Síria', value: 'Síria'},
  {key: 'Somália', value: 'Somália'},
  {key: 'Sri Lanca', value: 'Sri Lanca'},
  {key: 'Sudão', value: 'Sudão'},
  {key: 'Sudão do Sul', value: 'Sudão do Sul'},
  {key: 'Suécia', value: 'Suécia'},
  {key: 'Suíça', value: 'Suíça'},
  {key: 'Suriname', value: 'Suriname'},
  {key: 'Tailândia', value: 'Tailândia'},
  {key: 'Taiuã', value: 'Taiuã'},
  {key: 'Tajiquistão', value: 'Tajiquistão'},
  {key: 'Timor-Leste', value: 'Timor-Leste'},
  {key: 'Togo', value: 'Togo'},
  {key: 'Tonga', value: 'Tonga'},
  {key: 'Trindade e Tobago', value: 'Trindade e Tobago'},
  {key: 'Tunísia', value: 'Tunísia'},
  {key: 'Turcomenistão', value: 'Turcomenistão'},
  {key: 'Turquia', value: 'Turquia'},

  {key: 'Tuvalu', value: 'Tuvalu'},
  {key: 'Ucrânia', value: 'Ucrânia'},
  {key: 'Uganda', value: 'Uganda'},
  {key: 'Uruguai', value: 'Uruguai'},
  {key: 'Usbequistão', value: 'Usbequistão'},
  {key: 'Vanuatu', value: 'Vanuatu'},
  {key: 'Vaticano', value: 'Vaticano'},
  {key: 'Venezuela', value: 'Venezuela'},
  {key: 'Vietname', value: 'Vietname'},
];
export default countries3;
