/* eslint-disable prettier/prettier */
/* eslint-disable no-trailing-spaces */
/* eslint-disable quotes */
/* eslint-disable prettier/prettier */

const districts = {
    
  Niassa: [
    "Chimbunila",
    "Cuamba",
    "Lago",
    "Lichinga",
    "Majune",
    "Mandimba",
    "Marrupa",
    "Maúa",
    "Mavago",
    "Mecanhelas",
    "Mecula",
    "Metarica",
    "Muembe",
    "N'gauma",
    "Nipepe",
    "Sanga",
  ],

  Nampula: [
    "Angoche",
    "Eráti",
    "Ilha de Moçambique",
    "Lalaua",
    "Larde",
    "Liúpo",
    "Malema",
    "Meconta",
    "Mecubúri",
    "Memba",
    "Mogincual",
    "Mogovolas",
    "Moma",
    "Monapo",
    "Mossuril",
    "Muecate",
    "Murrupula",
    "Nacala",
    "Nacala-a-Velha",
    "Nacarôa",
    "Nampula",
    // "Nampula (Cidade)",
    "Rapale",
    "Ribáuè",
  ],

  "Cabo Delgado": [
    "Ancuabe",
    "Balama",
    "Chiúre",
    "Ibo",
    "Macomia",
    "Mecúfi",
    "Meluco",
    "Metuge",
    "Mocímboa da Praia",
    "Montepuez",
    "Mueda",
    "Muidumbe",
    "Namuno",
    "Nangade",
    "Palma",
    "Pemba (Cidade)",
    "Quissanga",
  ],

  Zambézia: [
    "Alto Molócuè",
    "Chinde",
    "Derre",
    "Gilé",
    "Gurué",
    "Ile",
    "Inhassunge",
    "Luabo",
    "Lugela",
    "Maganja da Costa",
    "Milange",
    "Mocuba",
    "Mocubela",
    "Molumbo",
    "Mopeia",
    "Morrumbala",
    "Mulevala",
    "Namacurra",
    "Namarroi",
    "Nicoadala",
    "Pebane",
    "Quelimane (Cidade)",
  ],

  Tete: [
    "Angónia",
    "Cahora-Bassa",
    "Changara",
    "Chifunde",
    "Chiuta",
    "Dôa",
    "Macanga",
    "Magoé",
    "Marara",
    "Marávia",
    "Moatize",
    "Mutarara",
    "Tete (Cidade)",
    "Tsangano",
    "Zumbo",
  ],

  Gaza: [
    "Bilene",
    "Chibuto",
    "Chicualacuala",
    "Chigubo",
    "Chókwè",
    "Chongoene",
    "Guijá",
    "Limpopo",
    "Mabalane",
    "Mandlakazi",
    "Mapai",
    "Massangena",
    "Massingir",
    "Xai-Xai (Cidade)",
  ],

  Maputo: [
    "Boane",
    "Magude",
    "Manhiça",
    "Marracuene",
    "Matola",
    "Matutuíne",
    "Moamba",
    "Namaacha",
  ],

  "Maputo (Cidade)": [
    "KaMpfumu",
    "Nlhamankulu",
    "KaMaxakeni",
    "KaMavota",
    "KaMubukwana",
    "KaTembe",
    "KaNyaka",
  ],

  Manica: [
    "Bárue",
    "Chimoio (Cidade)",
    "Gondola",
    "Guro",
    "Macate",
    "Machaze",
    "Macossa",
    "Manica",
    "Mossurize",
    "Sussundenga",
    "Tambara",
    "Vanduzi",
  ],

  Inhambane: [
    "Funhalouro",
    "Govuro",
    "Homoíne",
    "Inhambane (Cidade)",
    "Inharrime",
    "Inhassoro",
    "Jangamo",
    "Mabote",
    "Massinga",
    "Maxixe",
    "Morrumbene",
    "Panda",
    "Vilankulo",
    "Zavala",
  ],

  Sofala: [
    "Beira (Cidade)",
    "Búzi",
    "Caia",
    "Chemba",
    "Cheringoma",
    "Chibabava",
    "Dondo",
    "Gorongosa",
    "Machanga",
    "Maringué",
    "Marromeu",
    "Muanza",
    "Nhamatanda",
  ],

  
};

export default districts;
