
export const ordinalNumberings = {
 '1': 'primeira',
 '2': 'segunda',
 '3': 'terceira',
 '4': 'quarta',
 '5': 'quinta',
 '6': 'sexta',
 '7': 'sétima',
 '8': 'oitava',
 '9': 'nona',
 '10': 'décima',
 '11': 'décima e primeira',
 '12': 'décima e segunda',
 '13': 'décima e terceira',
 '14': 'décima e quarta',
 '15': 'décima e quinta',
 '16': 'décima e sexta',
 '17': 'décima e sétima',
 '18': 'décima e oitava',
 '19': 'décima e nova',
 '20': 'vigésima',
 '21': 'vigésima e primeira',
 '22': 'vigésima e segunda',
 '23': 'vigésima e terceira',
 '24': 'vigésima e quarta',
 '25': 'vigésima e quinta',
 '26': 'vigésima e sexta',
 '27': 'vigésima e sétima',
 '28': 'vigésima e oitava',
 '29': 'vigésima e nova', 
}