export const positions = {
    '1': 'Primeiro',
    '2': 'Segundo',
    '3': 'Terceiro',
    '4': 'Quarto',
    '5': 'Quinto',
    '6': 'Sexto',
    '7': 'Sétimo',
    '8': 'Oitavo',
    '9': 'Nono',
    '10': 'Décimo',
    '11': 'Décimo primeiro',
    '12': 'Décimo segundo',
    '13': 'Décimo terceiro',
    '14': 'Décimo quarto',
    '15': 'Décimo quinto',
    '16': 'Décimo sexto',
    '17': 'Décimo sétimo',
}